//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GameUpdate.rc
//
#define IDC_MODIFY_INSURE_PASSWORD      2
#define IDC_DEFAULT                     3
#define IDC_CLOSE_SERVER                4
#define IDC_CLOSE_PLAZA                 5
#define IDC_HAND_CUR                    130
#define IDD_DLG_STATU                   174
#define IDI_DOWNLOAD                    212
#define IDR_PNG1                        455
#define IDR_PNG2                        457
#define IDR_PNG3                        462
#define IDB_BITMAP1                     464
#define IDR_PNG4                        474
#define BT_SERVER_ITEM_VIEW             475
#define IDB_BITMAP2                     476
#define IDR_PNG5                        477
#define IDR_PNG6                        484
#define IDR_PNG7                        485
#define IDR_PNG8                        487
#define IDB_BT_CLOSE_BACK               490
#define IDB_BT_SELFUPDATE_BACK          493
#define IDC_SELECT_FACE                 1000
#define IDC_FACE_ITEM                   1001
#define IDC_SERVER_NAME                 1001
#define IDC_TABLE_PASSWORD              1006
#define IDC_NODE_ID                     1007
#define IDC_MIN_ENTER_MEMBER            1009
#define IDC_SEARCH_ONE_NULL             1010
#define IDC_MAX_ENTER_MEMBER            1010
#define IDC_GIVE_UP                     1011
#define IDC_REM_PASSWORD                1012
#define IDC_CANCEL_ONE                  1012
#define IDC_RETRY_AGAIN                 1013
#define IDC_REGISTER                    1013
#define IDC_SORT_ID                     1013
#define IDC_SEARCH_TWO_NULL             1014
#define IDC_SEARCH_NOT_FULL             1017
#define IDC_SEARCH_ALL_NULL             1019
#define IDC_LOGON_PASS1                 1020
#define IDC_INSURE_PASS1                1021
#define IDC_FILTRATE_PASS               1022
#define IDC_KIND_ID                     1022
#define IDC_QUIT                        1026
#define IDC_RESTRICT_SCORE              1026
#define IDC_MIN_ENTER_SCORE             1027
#define IDC_VALIDATE_CODE_WND           1028
#define IDC_MAX_ENTER_SCORE             1028
#define IDC_MIN_TABLE_SCORE             1029
#define IDC_USER_LIST_CONTROL           1030
#define IDC_REVENUE_RATIO               1030
#define IDC_PROXY_TEST                  1031
#define IDC_PROXY_TYPE                  1033
#define IDC_GENDER_MANKIND              1033
#define IDC_PROXY_SERVER                1034
#define IDC_GENDER_FEMALE               1034
#define IDC_CHAT_MESSAGE                1035
#define IDC_CHANGE_VALIDATE             1035
#define IDC_PROXY_USER                  1036
#define IDC_VIEW_CONTROL                1037
#define IDC_PROXY_PORT                  1038
#define IDC_PROXY_PASS                  1040
#define IDC_EDIT_PASSWD                 1042
#define IDC_PASSWD                      1042
#define IDC_PASSWD2                     1043
#define IDC_BUTTON1                     1043
#define IDC_CANCEL                      1043
#define IDC_BT_QUIT_SERVER              1045
#define IDC_BT_TABLE_BUTTON_5           1046
#define IDC_BT_TABLE_BUTTON_4           1047
#define IDC_BT_TABLE_BUTTON_1           1049
#define IDC_AUTO_JOIN                   1049
#define IDC_BT_TABLE_BUTTON_2           1050
#define IDC_BT_TABLE_BUTTON_3           1051
#define IDC_TAKE_PASSWORD               1054
#define IDC_CHAT_EDIT                   1055
#define IDC_BT_SEND_CHAT                1056
#define IDC_ACCOUNTS                    1057
#define IDC_LOGON_SERVER                1058
#define IDC_NICKNAME                    1058
#define IDC_PASSWORD                    1059
#define IDC_BT_CHAT_BUTTON_1            1060
#define IDC_QQ                          1060
#define IDC_LOGON_PASSWORD2             1060
#define IDC_SEAT_PHONE                  1061
#define IDC_LOGON_PASSWORD3             1061
#define IDC_LOGON_PASS2                 1061
#define IDC_BT_CHAT_BUTTON_2            1062
#define IDC_MOBILE_PHONE                1062
#define IDC_INSURE_PASSWORD2            1062
#define IDC_INSURE_PASS2                1062
#define IDC_PASSPORT_ID                 1063
#define IDC_EMAIL                       1063
#define IDC_INSURE_PASSWORD3            1063
#define IDC_BT_CHAT_BUTTON_3            1064
#define IDC_SPREADER                    1064
#define IDC_DWELLING_PLACE              1064
#define IDC_LAST                        1065
#define IDC_COMPELLATION                1065
#define IDC_BT_CHAT_BUTTON_4            1066
#define IDC_VALIDATE_CODE               1066
#define IDC_USER_NOTE                   1066
#define IDC_NEXT                        1067
#define IDC_VOR_SPLITER                 1071
#define IDC_HOR_SPLITER                 1073
#define IDC_LIMIT_SAME_IP               1079
#define IDC_SWITCH_ACCOUNTS             1080
#define IDC_LIMIT_FLEE_RATE             1081
#define IDC_BT_CHAT_SHORT               1082
#define IDC_LIMIT_GAME_SCORE            1083
#define IDC_LIMIT_DETEST                1088
#define IDC_LIMIT_WIN_RATE              1090
#define IDC_WIN_RATE                    1092
#define IDC_GAME_SCORE_MIN              1095
#define IDC_MESSAGE_SHOW_ALL            1108
#define IDC_MESSAGE_ONLY_FRIEND         1109
#define IDC_MESSAGE_HIDE_DETEST         1111
#define IDC_INVITE_ALL                  1113
#define IDC_INVITE_ONLY_FRIEND          1115
#define IDC_GAME_SCORE_MAX              1117
#define IDC_INVITE_NONE                 1118
#define IDC_AUTO_SHOW_WHISPER           1120
#define IDC_SHOW_WHISPER_BY_HOTKEY      1121
#define IDC_WHISPER_HOTKEY              1122
#define IDC_NOTIFY_USER_INOUT           1123
#define IDC_ALLOW_SOUND                 1124
#define IDC_FULL_SCREEN_BROWSE          1125
#define IDC_SNED_WHISPER_BY_ENTER       1126
#define IDC_AUTO_SAVE_WHISPER           1127
#define IDC_SNED_WHISPER_BY_CTRL_ENTER  1128
#define IDC_AUTO_SIT_DOWN               1129
#define IDC_SALIENCE_TABLE              1131
#define IDC_NOTIFY_FRIEND_COME          1133
#define IDC_BOSS_HOTKEY                 1135
#define IDC_ACTION_SEND_WHISPER         1137
#define IDC_ACTION_SHOW_USER_INFO       1140
#define IDC_ACTION_SEARCH_TABLE         1141
#define IDC_SHOW_SEARCH_TABLE_DLG       1142
#define IDC_ACTION_ORIENTATION          1143
#define IDC_FLEE_RATE                   1158
#define IDC_UNDER_WRITE                 1168
#define IDC_LOGON_PASSWORD1             1181
#define IDC_INSURE_PASSWORD1            1182
#define IDC_MODIFY_LOGON_PASSWORD       1183
#define IDC_NOTE                        1184
#define IDC_STRING                      1201
#define IDC_TAB_FACE                    2002
#define IDD_DLG_INPUT_PASSWD1           3003
#define IDD_DLG_STATUS1                 3003
#define IDD_DLG_UPDATE_CHECK            3003
#define IDC_IMMEDIATE_WRITE_SCORE       9001
#define IDC_RECORD_GAME_SCORE           9002
#define IDC_RECORD_GAME_TRACK           9003
#define IDC_FORFEND_ROOM_CHAT           9004
#define IDC_FORFEND_WISPER_CHAT         9005
#define IDC_FORFEND_GAME_CHAT           9006
#define IDC_DYNAMIC_JOIN                9007
#define IDC_FORFEND_GAME_LOOKON         9008
#define IDC_FORFEND_GAME_ENTER          9009
#define IDC_OFFLINE_TRUSTEE             9010
#define IDC_AVERT_CHEAT_MODE            9011
#define IDC_ALLOW_ANDROID_USER          9012
#define IDC_FORFEND_ROOM_ENTER          9013
#define IDC_FORFEND_WISPER_ON_GAME      9014
#define IDC_FORFEND_GAME_RULE           9015
#define IDC_FORFEND_LOCK_TABLE          9016
#define IDC_FORFEND_SAVE_IN_GAME        9017
#define IDC_FORFEND_SAVE_IN_ROOM        9018
#define IDC_DYNAMIC_CELL_SCORE          9021
#define IDM_USER_LOGON                  32774
#define IDM_SWITCH_ACCOUNTS             32778
#define IDM_COPY_USER_NICKNAME          32779
#define IDM_SEE_USER_LOCATION           32780
#define IDM_SET_FRIEND_USER             32782
#define IDM_ENTER_SERVER                32784
#define IDM_EXPAND_LIST                 32788
#define IDM_SHRINK_LIST                 32790
#define IDM_MESSAGE_HIDE_DETEST         32791
#define IDM_MESSAGE_SHOW_ALL            32792
#define IDM_MESSAGE_ONLY_FRIEND         32793
#define IDM_DELETE_SERVER_ITEM          32794
#define IDM_MANAGER_MESSAGE             32795
#define IDM_GAME_RULE                   32798
#define IDM_GAME_CHART                  32799
#define IDM_CANCEL_CHAT_USER            32819
#define IDM_SET_CHAT_USER               32820
#define IDM_SEARCH_ONLINE_USER          32821
#define IDM_INVITE_USER                 32822
#define IDM_SHOW_USER_INFO              32826
#define IDM_SET_USER_NOTE               32827
#define IDM_USER_INFO_MANAGER           32830
#define IDM_LOOKON_USER                 32832
#define IDM_PLAY_GAME_TOGETHER          32834
#define IDM_SEND_BY_ENTER               32837
#define IDM_SEND_BY_CTRL_ENTER          32838
#define IDM_MORE_COLOR                  32840
#define IDM_MANAGER_SERVER              32859
#define IDM_MANAGER_ANDROID             32861
#define IDM_MANAGER_USER                32872
#define IDM_KILL_USER                   32874

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        494
#define _APS_NEXT_COMMAND_VALUE         32800
#define _APS_NEXT_CONTROL_VALUE         1044
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
