//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AndroidManager.rc
//
#define IDC_MODIFY_INSURE_PASSWORD      2
#define IDC_DEFAULT                     3
#define IDC_CLOSE_SERVER                4
#define IDC_CLOSE_PLAZA                 5
#define IDR_MAINFRAME                   128
#define IDC_HAND_CUR                    130
#define IDB_BT_CLOSE                    137
#define IDD_GAME_PLAZA                  149
#define IDD_PLATFORM_FRAME              149
#define IDB_BT_SKIN                     150
#define IDB_BT_MIN                      151
#define IDB_BT_MAX                      152
#define IDB_BT_RESORE                   153
#define IDR_COMMAND                     166
#define IDD_DLG_STATUS                  168
#define IDB_BT_COMBOBOX                 193
#define IDI_DOWNLOAD                    212
#define IDB_DOWN_LOAD_ITEM              213
#define IDB_BT_SEND_CHAT                307
#define IDI_WHISPER                     367
#define IDB_BT_LOGON_LINK               384
#define IDD_DLG_LOGON                   385
#define IDB_BT_LOGON                    387
#define IDB_BT_LOGON_QUIT               389
#define IDB_BT_LOGON_ITEM               391
#define IDB_IMAGE_REGISTER              396
#define IDI_NULL                        416
#define IDB_IMAGE_SEARCH                417
#define IDB_REMOTE_USER_IMAGE           419
#define IDB_BT_STATUS_CANCEL            423
#define IDR_PNG1                        425
#define IDD_DIALOG1                     427
#define IDB_SHIELD_WHISPER              431
#define IDB_RECEVE_WHISPER              432
#define IDB_SET_FRIEND                  433
#define IDB_CANCEL_FRIEND               434
#define IDB_SET_DETEST                  435
#define IDB_CANCEL_DETEST               436
#define IDB_MESSAGE_SETTING             439
#define IDC_SELECT_FACE                 1000
#define IDC_FACE_ITEM                   1001
#define IDC_SERVER_NAME                 1001
#define IDC_WEB_STOP                    1005
#define IDC_TABLE_PASSWORD              1006
#define IDC_NODE_ID                     1007
#define IDC_WEB_RELOAD                  1008
#define IDC_WEB_HOME                    1009
#define IDC_MIN_ENTER_MEMBER            1009
#define IDC_DELETE_RECORD               1010
#define IDC_SEARCH_ONE_NULL             1010
#define IDC_MAX_ENTER_MEMBER            1010
#define IDC_GIVE_UP                     1011
#define IDC_REM_PASSWORD                1012
#define IDC_CANCEL_ONE                  1012
#define IDC_RETRY_AGAIN                 1013
#define IDC_REGISTER                    1013
#define IDC_SORT_ID                     1013
#define IDC_SEARCH_TWO_NULL             1014
#define IDC_SEARCH_NOT_FULL             1017
#define IDC_BT_LOGON_LINK_2             1018
#define IDC_BT_LOGON_LINK_3             1019
#define IDC_SEARCH_ALL_NULL             1019
#define IDC_PROXY_CONFIG                1020
#define IDC_LOGON_PASS1                 1020
#define IDC_WEB_LAST                    1021
#define IDC_TAB_CONTROL                 1021
#define IDC_INSURE_PASS1                1021
#define IDC_CHAT_INPUT                  1022
#define IDC_BT_LOGON_LINK_4             1022
#define IDC_FILTRATE_PASS               1022
#define IDC_KIND_ID                     1022
#define IDC_WEB_NEXT                    1024
#define IDC_GAME_ID                     1024
#define IDC_BT_LOGON_LINK_1             1025
#define IDC_MODE_NAME                   1026
#define IDC_QUIT                        1026
#define IDC_RESTRICT_SCORE              1026
#define IDC_MIN_ENTER_SCORE             1027
#define IDC_VALIDATE_CODE_WND           1028
#define IDC_MAX_ENTER_SCORE             1028
#define IDC_BT_USER_MENU                1029
#define IDC_MIN_TABLE_SCORE             1029
#define IDC_USER_LIST_CONTROL           1030
#define IDC_REVENUE_RATIO               1030
#define IDC_SERVICE_REVENUE             1030
#define IDC_PROXY_TEST                  1031
#define IDC_SEARCH_AREA                 1031
#define IDC_REVENUE_RATIO2              1031
#define IDC_SERVICE_SCORE               1031
#define IDC_REVENUE_RADIO               1031
#define IDC_SEARCH_REMOTE               1032
#define IDC_PROXY_TYPE                  1033
#define IDC_GENDER_MANKIND              1033
#define IDC_SEARCH_BY_GAME_ID           1033
#define IDC_PROXY_SERVER                1034
#define IDC_GENDER_FEMALE               1034
#define IDC_SEARCH_NAME                 1034
#define IDC_CHAT_MESSAGE                1035
#define IDC_CHANGE_VALIDATE             1035
#define IDC_STATIC_IMAGE                1035
#define IDC_PROXY_USER                  1036
#define IDC_USER_LIST_REMOTE            1036
#define IDC_VIEW_CONTROL                1037
#define IDC_USER_LIST_NATIVE            1037
#define IDC_PROXY_PORT                  1038
#define IDC_PROXY_PASS                  1040
#define IDC_RICHEDIT21                  1040
#define IDC_EDT_HISTORY                 1040
#define IDC_ADD_FRIEND                  1041
#define IDC_SET_DETEST                  1042
#define IDC_SHIELD_THIS_CHAT            1044
#define IDC_BT_QUIT_SERVER              1045
#define IDC_BUTTON4                     1045
#define IDC_MESSAGE_SETTING             1045
#define IDC_BT_TABLE_BUTTON_5           1046
#define IDC_BT_TABLE_BUTTON_4           1047
#define IDC_BT_TABLE_BUTTON_1           1049
#define IDC_AUTO_JOIN                   1049
#define IDC_ISSUE_MESSAGE               1049
#define IDC_BT_TABLE_BUTTON_2           1050
#define IDC_DISMISS_GAME                1050
#define IDC_BT_TABLE_BUTTON_3           1051
#define IDC_SEE_USER_IP                 1051
#define IDC_CHECK_ALLROOM               1052
#define IDC_EDIT_TALBER_NUM             1053
#define IDC_EDIT_TABLE_NUM              1053
#define IDC_TAKE_PASSWORD               1054
#define IDC_INPUT                       1054
#define IDC_AGREEITEMS                  1054
#define IDC_CHAT_EDIT                   1055
#define IDC_CHECK1                      1055
#define IDC_CHECK_AGREEITEMS            1055
#define IDC_CHECK_SERVICE_MODE1         1055
#define IDC_BT_SEND_CHAT                1056
#define IDC_ED_PHONE                    1056
#define IDC_CHECK_SERVICE_MODE2         1056
#define IDC_ACCOUNTS                    1057
#define IDC_CHECK_SERVICE_MODE3         1057
#define IDC_LOGON_SERVER                1058
#define IDC_NICKNAME                    1058
#define IDC_PASSWORD                    1059
#define IDC_ED_EMEIL                    1059
#define IDC_ED_EMAIL                    1059
#define IDC_BT_CHAT_BUTTON_1            1060
#define IDC_QQ                          1060
#define IDC_LOGON_PASSWORD2             1060
#define IDC_ED_QQ                       1060
#define IDC_SEAT_PHONE                  1061
#define IDC_LOGON_PASSWORD3             1061
#define IDC_LOGON_PASS2                 1061
#define IDC_COMBO_GAME                  1061
#define IDC_BT_CHAT_BUTTON_2            1062
#define IDC_MOBILE_PHONE                1062
#define IDC_INSURE_PASSWORD2            1062
#define IDC_INSURE_PASS2                1062
#define IDC_COMBO_SERVER                1062
#define IDC_PASSPORT_ID                 1063
#define IDC_EMAIL                       1063
#define IDC_INSURE_PASSWORD3            1063
#define IDC_BT_QUERY                    1063
#define IDC_BT_CHAT_BUTTON_3            1064
#define IDC_SPREADER                    1064
#define IDC_DWELLING_PLACE              1064
#define IDC_LIST_PARAMETER              1064
#define IDC_LAST                        1065
#define IDC_COMPELLATION                1065
#define IDC_EDIT_ANDROID_COUNT          1065
#define IDC_BT_CHAT_BUTTON_4            1066
#define IDC_VALIDATE_CODE               1066
#define IDC_USER_NOTE                   1066
#define IDC_COMBO_ENTER_HOUR            1066
#define IDC_NEXT                        1067
#define IDC_COMBO_ENTER_MINUTE          1067
#define IDC_COMBO_ENTER_SECOND          1068
#define IDC_COMBO_LEAVE_HOUR            1069
#define IDC_COMBO_LEAVE_MINUTE          1070
#define IDC_VOR_SPLITER                 1071
#define IDC_COMBO_LEAVE_SECOND          1071
#define IDC_EDIT_ENTERINTERVAL_MIN      1072
#define IDC_HOR_SPLITER                 1073
#define IDC_EDIT_ENTERINTERVAL_MAX      1073
#define IDC_EDIT_LEAVEINTERVAL_MIN      1074
#define IDC_EDIT_LEAVEINTERVAL_MAX      1075
#define IDC_EDIT_SWITCHTABLE_MIN        1076
#define IDC_EDIT_SWITCHTABLE_MAX        1077
#define IDC_EDIT_TAKESCORE_MIN          1078
#define IDC_LIMIT_SAME_IP               1079
#define IDC_EDIT_TAKESCORE_MAX          1079
#define IDC_SWITCH_ACCOUNTS             1080
#define IDC_BT_ADD                      1080
#define IDC_LIMIT_FLEE_RATE             1081
#define IDC_BT_MODIFY                   1081
#define IDC_BT_CHAT_SHORT               1082
#define IDC_BUTTON5                     1082
#define IDC_BT_DELETE                   1082
#define IDC_LIMIT_GAME_SCORE            1083
#define IDC_EDIT_COUNT_MEMBER0          1083
#define IDC_BT_CHAT_HISTORY             1084
#define IDC_EDIT_COUNT_MEMBER1          1084
#define IDC_EDIT_COUNT_MEMBER2          1085
#define IDC_EDIT_COUNT_MEMBER3          1086
#define IDC_EDIT_COUNT_MEMBER4          1087
#define IDC_LIMIT_DETEST                1088
#define IDC_EDIT_COUNT_MEMBER5          1088
#define IDC_BT_SEND_CONTROL             1089
#define IDC_RADIO_CONTINUE_DRAW         1089
#define IDC_LIMIT_WIN_RATE              1090
#define IDC_CHAT_SPLITTER               1091
#define IDC_WIN_RATE                    1092
#define IDC_INFO_SPLITTER               1093
#define IDC_GAME_SCORE_MIN              1095
#define IDC_MESSAGE_SHOW_ALL            1108
#define IDC_MESSAGE_ONLY_FRIEND         1109
#define IDC_LIMIT_WISPER                1110
#define IDC_MESSAGE_HIDE_DETEST         1111
#define IDC_LIMIT_ROOM_CHAT             1112
#define IDC_INVITE_ALL                  1113
#define IDC_LIMIT_ENTER_GAME            1114
#define IDC_INVITE_ONLY_FRIEND          1115
#define IDC_LIMIT_PLAY_CHAT             1115
#define IDC_LIMIT_GAME_CHAT             1116
#define IDC_GAME_SCORE_MAX              1117
#define IDC_LIMIT_REMOTE_SEARCH         1117
#define IDC_INVITE_NONE                 1118
#define IDC_LIMIT_ENTER_ANDROID         1118
#define IDC_LIMIT_ENTER_ROOM            1119
#define IDC_AUTO_SHOW_WHISPER           1120
#define IDC_FORBID_MEMBER_CAN_CHAT      1120
#define IDC_SHOW_WHISPER_BY_HOTKEY      1121
#define IDC_FORBID_LOOKON               1121
#define IDC_WHISPER_HOTKEY              1122
#define IDC_FORBID_LOOKON_CHAT          1122
#define IDC_NOTIFY_USER_INOUT           1123
#define IDC_ALLOW_LOOKON_CHAT           1123
#define IDC_ALLOW_SOUND                 1124
#define IDC_FULL_SCREEN_BROWSE          1125
#define IDC_SNED_WHISPER_BY_ENTER       1126
#define IDC_ALLOW_BACKMUSIC             1126
#define IDC_ALLOW_MEMBER_LOOKON_CHAT    1126
#define IDC_AUTO_SAVE_WHISPER           1127
#define IDC_SNED_WHISPER_BY_CTRL_ENTER  1128
#define IDC_AUTO_SIT_DOWN               1129
#define IDC_ALLOW_WISPER                1130
#define IDC_SALIENCE_TABLE              1131
#define IDC_ALLOW_ROOM_CHAT             1132
#define IDC_NOTIFY_FRIEND_COME          1133
#define IDC_ALLOW_ENTER_GAME            1134
#define IDC_BOSS_HOTKEY                 1135
#define IDC_ALLOW_PLAY_CHAT             1135
#define IDC_ALLOW_GAME_CHAT             1136
#define IDC_ACTION_SEND_WHISPER         1137
#define IDC_ALLOW_REMOTE_SEARCH         1137
#define IDC_ALLOW_ENTER_ROOM            1138
#define IDC_ALLOW_ENTER_ANDROID         1139
#define IDC_ACTION_SHOW_USER_INFO       1140
#define IDC_ALLOW_MEMBER_CAN_CHAT       1140
#define IDC_ACTION_SEARCH_TABLE         1141
#define IDC_ALLOW_LOOKON                1141
#define IDC_SHOW_SEARCH_TABLE_DLG       1142
#define IDC_ACTION_ORIENTATION          1143
#define IDC_FLEE_RATE                   1158
#define IDC_UNDER_WRITE                 1168
#define IDC_LOGON_PASSWORD1             1181
#define IDC_INSURE_PASSWORD1            1182
#define IDC_MODIFY_LOGON_PASSWORD       1183
#define IDC_NOTE                        1184
#define IDC_KICK_ALL_USER               1191
#define IDC_EDT_MESSAGE                 1192
#define IDC_CHEK_GAME                   1197
#define IDC_CHEK_ROOM                   1198
#define IDC_STRING                      1201
#define IDC_TAB_FACE                    2002
#define IDC_IMMEDIATE_WRITE_SCORE       9001
#define IDC_RECORD_GAME_SCORE           9002
#define IDC_RECORD_GAME_TRACK           9003
#define IDC_FORFEND_ROOM_CHAT           9004
#define IDC_FORFEND_WISPER_CHAT         9005
#define IDC_FORFEND_GAME_CHAT           9006
#define IDC_DYNAMIC_JOIN                9007
#define IDC_ALLOW_DYNAMIC_JOIN          9007
#define IDC_FORFEND_GAME_LOOKON         9008
#define IDC_FORFEND_GAME_ENTER          9009
#define IDC_OFFLINE_TRUSTEE             9010
#define IDC_ALLOW_OFFLINE_TRUSTEE       9010
#define IDC_AVERT_CHEAT_MODE            9011
#define IDC_ALLOW_AVERT_CHEAT_MODE      9011
#define IDC_ALLOW_ANDROID_USER          9012
#define IDC_ALLOW_ANDROID_ATTEND        9012
#define IDC_FORFEND_ROOM_ENTER          9013
#define IDC_FORFEND_WISPER_ON_GAME      9014
#define IDC_FORFEND_GAME_RULE           9015
#define IDC_FORFEND_LOCK_TABLE          9016
#define IDC_FORFEND_SAVE_IN_GAME        9017
#define IDC_FORFEND_SAVE_IN_ROOM        9018
#define IDC_FORBID_WINRATE              9019
#define IDC_ALLOW_ANDROID_SIMULATE      9019
#define IDC_FORBID_FLEERATE             9020
#define IDC_DYNAMIC_CELL_SCORE          9021
#define IDC_FORBID_SCORELIMIT           9021
#define IDC_FORBID_BLACK                9022
#define IDC_STATIC_REVENUE_SERVICE      9022
#define IDC_FORBID_IPSET                9023
#define IDC_SERVICE_RADIO               9024
#define IDC_FORBID_PASSWORD             9025
#define IDM_USER_LOGON                  32774
#define IDM_SWITCH_ACCOUNTS             32778
#define IDM_COPY_USER_NICKNAME          32779
#define IDM_SEE_USER_LOCATION           32780
#define IDM_CREATE_ISER_WISPER          32781
#define IDM_ENTER_SERVER                32784
#define IDM_ENTER_TABLE                 32785
#define IDM_EXPAND_LIST                 32788
#define IDM_SHRINK_LIST                 32790
#define IDM_MESSAGE_HIDE_DETEST         32791
#define IDM_MESSAGE_SHOW_ALL            32792
#define IDM_MESSAGE_ONLY_FRIEND         32793
#define IDM_DELETE_SERVER_ITEM          32794
#define IDM_MANAGER_MESSAGE             32795
#define IDM_GAME_RULE                   32798
#define IDM_GAME_CHART                  32799
#define IDM_SET_FRIEND_USER             32801
#define IDM_SET_DETEST_USER             32802
#define IDM_NULL_COMMAND                32803
#define ID_Menu                         32804
#define ID_Menu32805                    32805
#define IDM_CANCEL_CHAT_USER            32819
#define IDM_SET_CHAT_USER               32820
#define IDM_SEARCH_ONLINE_USER          32821
#define IDM_INVITE_USER                 32822
#define IDM_SHOW_USER_INFO              32826
#define IDM_SET_USER_NOTE               32827
#define IDM_USER_INFO_MANAGER           32830
#define IDM_LOOKON_USER                 32832
#define IDM_PLAY_GAME_TOGETHER          32834
#define IDM_SEND_BY_ENTER               32837
#define IDM_SEND_BY_CTRL_ENTER          32838
#define IDM_MORE_COLOR                  32840
#define IDM_SEARCH_TABLE                32844
#define IDM_ISSUE_MESSAGE               32858
#define IDM_MANAGER_SERVER              32859
#define IDM_MANAGER_USER                32872
#define IDM_KILL_USER                   32874
#define IDM_LIMIT_USER_ROOM_CHAT        32892
#define IDM_ALLOW_USER_ROOM_CHAT        32894
#define IDM_LIMIT_USER_GAME_CHAT        32896
#define IDM_LIMIT_USER_WHISP_CHAT       32899
#define IDM_ALLOW_USER_WHISP_CHAT       32901
#define IDM_ALLOW_USER_GAME_CHAT        32902

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        441
#define _APS_NEXT_COMMAND_VALUE         32806
#define _APS_NEXT_CONTROL_VALUE         1091
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
