//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GameClient.rc
//
#define IDR_MAINFRAME                   100
#define IDB_HAND                        101
#define IDB_FRAME                       102
#define IDB_FRAME_R                     103
#define IDB_FRAME_L                     104
#define IDB_FRAME_M                     105
#define IDB_FRAME_EX                    106
#define IDB_CARDTYPE                    107
#define IDB_TIME_FLAG                   111
#define IDB_WIN_FLAGS                   112
#define IDB_VIEW_BACK                   113
#define IDB_VIEW_FILL                   114
#define IDB_GAME_CARD                   115
#define IDB_SCORE_NUMBER                117
#define IDB_CONTINUE_CARD               118
#define IDB_DISPATCH_CARD               119
#define IDB_APPLY_USER_BACK             121
#define IDB_ME_SCORE_NUMBER             122
#define IDB_SCROLL_BAR                  130
#define IDB_SKIN_SCROLL                 131
#define IDB_LIST_TITLE					132
#define	IDB_USER_STATUS_IMAGE			133
#define IDB_BT_MIN_BUTTON				134
#define IDB_BT_CLOSE_BUTTON				135
#define IDB_BT_SOUND_OPEN				136
#define IDB_BT_SOUND_CLOSE				137
#define IDB_BT_OPTION					138
#define IDB_BT_USER_LIST				139
#define IDB_BT_CHAT						140
#define IDB_BT_SEND_MESSAGE				141
#define IDB_BT_BT_S                     300
#define IDB_BT_BT_X                     301
#define IDB_BT_OPEN_CARD                305
#define IDB_BT_SCORE_MOVE_L             306
#define IDB_BT_SCORE_MOVE_R             307
#define IDB_BT_CANCEL_APPLY             308
#define IDB_BT_APPLY_BANKER             309
#define IDB_BT_CANCEL_BANKER            310
#define IDB_BT_CONTINUE_CARD            311
#define IDB_BT_AUTO_OPEN_CARD           312
#define IDB_BT_CLOSE                    313
#define IDB_GETGOLD                     314
#define IDB_SAVEGOLD                    315
#define IDB_CLOSE                       316
#define IDB_BT_FRESH                    317
#define IDD_OPTION                      400
#define IDD_DLG_GAME_RECORD             402
#define IDC_BT_CLOSE                    403
#define STATIC_PASS                     1000
#define IDC_RADIO1                      1001
#define IDC_RADIOSTORE                  1002
#define IDC_ALLOWLOOKON                 1003
#define IDC_TEXT_CAPTION                1004
#define IDC_RADIOGET                    1005
#define IDC_ENABLE_SOUND                1006
#define IDC_RECORD_LIST                 1007
#define IDB_BT_DRAW                     2000
#define IDB_BT_STORAGE                  2001
#define IDC_IN_COUNT                    2002
#define IDC_BANK_DRAW                   2003
#define IDC_GAME_GOLD                   2004
#define IDC_STATIC_PASS                 2005
#define IDC_BANK_STORAGE                2006
#define IDD_BANK_STORAGE                2007
#define IDC_STORAGE_GOLD                2008
#define IDC_USER_PASSWORD               2009
#define IDC_CHECK_ALL                   2010
#define IDC_BT_LOOK_RECORD              2010
#define IDB_BT_LOOK_RECORD              2011
#define IDI_SCORE_500                   3000
#define IDI_SCORE_1000                  3001
#define IDI_SCORE_10000                 3002
#define IDI_SCORE_100000                3003
#define IDI_SCORE_1000000               3004
#define IDI_SCORE_5000000               3005
#define IDI_SCORE_10000000              3006
#define IDB_BT_JETTON_500               3100
#define IDB_BT_JETTON_1000              3101
#define IDB_BT_JETTON_10000             3102
#define IDB_BT_JETTON_100000            3103
#define IDB_BT_JETTON_1000000           3104
#define IDB_BT_JETTON_5000000           3105
#define IDB_BT_JETTON_10000000          3106
#define IDC_JETTON_BUTTON_500           3200
#define IDC_JETTON_BUTTON_1000          3201
#define IDC_JETTON_BUTTON_10000         3202
#define IDC_JETTON_BUTTON_100000        3203
#define IDC_JETTON_BUTTON_1000000       3204
#define IDC_JETTON_BUTTON_5000000       3205
#define IDC_JETTON_BUTTON_10000000      3206
#define IDC_BT_RESET                    4000
#define IDC_BT_CURSET                   4001
#define IDC_BT_EXCUTE                   4002
#define IDC_BT_CANCEL                   4003
#define IDC_COMBO_TIMES                 4004
#define IDC_RADIO_WIN                   4005
#define IDC_RADIO_LOSE                  4006
#define IDC_RADIO_CT_BANKER             4007
#define IDC_RADIO_CT_AREA               4008
#define IDC_CHECK_TIAN                  4009
#define IDC_CHECK_DI                    4010
#define IDC_CHECK_XUAN                  4011
#define IDC_BT_ADMIN                    4101
#define IDC_STATIC_TIMES                4102
#define IDC_STATIC_CHOICE               4103
#define IDC_STATIC_NOTICE               4104
#define IDC_STATIC_NOTICE1              4105
#define IDC_STATIC_NOTICE2              4106
#define IDC_COMBO_SICBO_ONE             4107
#define IDC_COMBO_SICBO_TWO             4108
#define IDC_COMBO_SICBO_THREE           4109
#define IDC_STATIC_INFO                 4110
#define IDC_STATIC_STATE                4111
#define IDC_CARTOON_DICE                5100

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        254
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
